### ISSUE TITLE
Reaction failed message not appearing while simulation is run in normal mode

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#5]
Unless the model is run in verbose mode, "reaction failed" message doesn't appear. So even if reaction fails, there is no indication in normal mode. Only if we see the output file and see nan values, we can realize that the model has failed. Maybe we can add this message whether or not the model is run in verbose mode.

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan Where do you see the nan values? In the river?

**Comment by KayalvizhiSadayappan** [comment]
Yes nan values for stream concentration

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan This is not caused by reaction. This is caused by the 0 concentration in primary species, when Q0 = Q1 = Q2 = 0. I will skip speciation when discharge is 0.

**Comment by KayalvizhiSadayappan** [comment]
Also, can you ensure that if there is a failure of reaction, that message appears in normal mode too? Now it appears only in verbose mode. "Reaction failed" message should appear in normal mode. This is very important as model can take previous time step values and keep simulating and give results. So, the user on looking at the results might not realize there has been a mistake.

**Comment by KayalvizhiSadayappan** [comment]
I looked at the output files again but the nan values starts for a time step and then continues being nan. Before the day it starts to have nan values, there are other days with zero Q0, Q1 and Q2. I am sending you the input files and output I got in slack. Thanks!

**Comment by shiyuning** [comment]
The issue is caused by the instability of the forward-in-time scheme. For transport,

d(*CV*) / d*t* = *C*<sub>in</sub>*q*<sub>in</sub> - *Cq*<sub>out</sub>.

Using forward-in-time scheme, we have

*CV* - *C*<sub>0</sub>*V*<sub>0</sub> = *C*<sub>in</sub>*Q*<sub>in</sub> - *C*<sub>0</sub>*Q*<sub>out</sub>, i.e.,

*C* = (*C*<sub>in</sub>*Q*<sub>in</sub> - *C*<sub>0</sub>*Q*<sub>out</sub> + *C*<sub>0</sub>*V*<sub>0</sub>) / V.

This is unstable when *C*<sub>in</sub>*Q*<sub>in</sub> - *C*<sub>0</sub>*Q*<sub>out</sub> + *C*<sub>0</sub>*V*<sub>0</sub> < 0, e.g., dilution with a large out flux.

Switching to backward-in-time scheme would increase stability, in which

*C* = (*C*<sub>in</sub>*Q*<sub>in</sub> + *C*<sub>0</sub>*V*<sub>0</sub>) /  (V + *Q*<sub>out</sub>).
